---
- name: Add Secret
  uri:
    url: "https://graph.microsoft.com/v1.0/myorganization/applications/{{essentials_perimeter_object_id}}/addPassword"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ ad_token }}"
    body_format: json
    body: "{{ addSecret | to_json }}"
  register: addSecret
  failed_when: addSecret.status != 200 and addSecret.status != 201 and addSecret.status != 204

- name: Print addSecret
  debug:
    var: addSecret

- set_fact:
    secret: "{{addSecret.json.secretText}}"

- set_fact:
    secretId: "{{addSecret.json.keyId}}"


