---
# 791dc195-a359-4189-85d9-777c153c6312 collect from inspect element when install application on azure directory galery
- name: Instantiate p81
  uri:
    url: "https://graph.microsoft.com/v1.0/applicationTemplates/5f27f642-4cf6-4a69-b02d-45c1eac19161/instantiate"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ ad_token }}"
    body_format: json
    body: "{{ instantiateP81 | to_json }}"
  register: instantiateP81
  failed_when: instantiateP81.status != 200 and instantiateP81.status != 201 and instantiateP81.status != 204

- name: Print instantiateP81
  debug:
    var: instantiateP81.json

# same as object id
- set_fact:
    perimeter_id: "{{instantiateP81.json.servicePrincipal.id}}"

- set_fact:
    app_perimeter_id: "{{instantiateP81.json.application.appId}}"

- set_fact:
    essentials_perimeter_object_id: "{{instantiateP81.json.application.id}}"

- set_fact:
    perimeter_app_role_id: "{{instantiateP81.json.servicePrincipal.appRoles[0].id}}"

